const TIMERS_NOTCHES = [5, 15, 30, 60] as const
const LEVER_SIZE_MAX = 30
const LEVER_SIZE_MIN = 18
const ORBIT_PADDING_MIN = 44
const ORBIT_PADDING_MAX = 268
const SNAP_DISTANCE = 10
const CABLE_WIDTH_MAX = 3
const CABLE_WIDTH_MIN = 0.6
const RUBBER_STRENGTH_DOWN = 0.15
const RUBBER_STRENGTH_UP = 6.0

export {
  CABLE_WIDTH_MAX,
  CABLE_WIDTH_MIN,
  LEVER_SIZE_MAX,
  LEVER_SIZE_MIN,
  ORBIT_PADDING_MAX,
  ORBIT_PADDING_MIN,
  RUBBER_STRENGTH_DOWN,
  RUBBER_STRENGTH_UP,
  SNAP_DISTANCE,
  TIMERS_NOTCHES,
}
